# Generated by Django 4.2.5 on 2024-02-04 09:13

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filmwork",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Дата изменения записи")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_date", models.CharField(max_length=50, verbose_name="Дата производства")),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[(None, "Выбери тип кинопроизведения"), ("movie", "Фильм"), ("tv_show", "Телешоу")],
                        verbose_name="Тип кинопроизведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кинопроизведение",
                "verbose_name_plural": "Кинопроизведения",
                "db_table": 'content"."film_work',
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Дата изменения записи")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Наименование жанра")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "db_table": 'content"."genre',
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Дата изменения записи")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255, verbose_name="Полное имя")),
            ],
            options={
                "verbose_name": "Участник кинопроизведения",
                "verbose_name_plural": "Участники кинопроизведения",
                "db_table": 'content"."person',
                "ordering": ["-full_name"],
            },
        ),
        migrations.CreateModel(
            name="PersonFilmwork",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.TextField(verbose_name="role")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("film_work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.filmwork")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.person")),
            ],
            options={
                "db_table": 'content"."person_film_work',
            },
        ),
        migrations.CreateModel(
            name="GenreFilmwork",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("film_work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.filmwork")),
                ("genre", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.genre")),
            ],
            options={
                "db_table": 'content"."genre_film_work',
            },
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(fields=["-name"], name="genre_name_464984_idx"),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="genres",
            field=models.ManyToManyField(through="movies.GenreFilmwork", to="movies.genre"),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="person",
            field=models.ManyToManyField(through="movies.PersonFilmwork", to="movies.person"),
        ),
        migrations.AddIndex(
            model_name="filmwork",
            index=models.Index(fields=["-created"], name="film_work_created_71ba1a_idx"),
        ),
    ]
