# Generated by Django 4.2.5 on 2024-02-06 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"ordering": ["-created_date"], "verbose_name": "film work", "verbose_name_plural": "film works"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["-name"], "verbose_name": "genre", "verbose_name_plural": "genres"},
        ),
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={"verbose_name": "genre film work"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["full_name"], "verbose_name": "person", "verbose_name_plural": "persons"},
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={"verbose_name": "person film work"},
        ),
        migrations.RemoveIndex(
            model_name="filmwork",
            name="film_work_created_71ba1a_idx",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="genres",
            new_name="genre",
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_date"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="created_date",
            field=models.CharField(blank=True, verbose_name="year_of_release"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="update_date"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                blank=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[("movie", "movie"), ("tv_show", "tv_show")], default="movie", verbose_name="type"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_date"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="update_date"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, verbose_name="genre"),
        ),
        migrations.AlterField(
            model_name="genrefilmwork",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.genre", verbose_name="genre"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_date"),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="update_date"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.person", verbose_name="person"
            ),
        ),
        migrations.AddIndex(
            model_name="filmwork",
            index=models.Index(fields=["created_date"], name="film_work_created_0d91d2_idx"),
        ),
    ]
