# Generated by Django 4.2.5 on 2024-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_filmwork_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={"ordering": ["-creation_date"], "verbose_name": "film work", "verbose_name_plural": "film works"},
        ),
        migrations.RemoveIndex(
            model_name="filmwork",
            name="film_work_created_0d91d2_idx",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="created_date",
            new_name="creation_date",
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_date"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_date"),
        ),
        migrations.AlterField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_date"),
        ),
        migrations.AddIndex(
            model_name="filmwork",
            index=models.Index(fields=["creation_date"], name="film_work_creatio_02a6ad_idx"),
        ),
    ]
